language: bash
sudo: required
cache: apt

# we don't use docker but this triggers travis-ci to provide Ubuntu 14.04
services:
    - docker
before_install:
    - lsb_release -a
    - sudo apt-get update -qq
install:
    - sudo make dependencies
    - make local
script:
    # make test and create Debian package
    - make package
    # locally install package
    - sudo dpkg -i dbinfo_*.deb
    - sudo service dbinfo status
    # test against localhost
    - export TEST_URL=6006
    - prove -Ilib -Ilocal/lib/perl5 -v

after_failure:
    - tail -200 /var/log/dbinfo/error.log
