language: bash
before_install:
    - sudo make dependencies
install:
    # don't use perlbrew
    - sudo chown -R travis:travis /home/travis/.cpanm
    - carton install --deployment
script:
    - export PACKAGE=`perl -ne 'print $1 if /^Package:\s+(.+)/;' < debian/control`
    - make release-file
    - sudo dpkg -i ${PACKAGE}_*.deb
    - sudo service ${PACKAGE} status
    - sudo service ${PACKAGE} restart
    - carton exec prove -Ilib --verbose
cache: apt
