.TH "DBINFO" "1" "" "Manual" ""
.SH NAME
.PP
dbinfo \- GBV Datenbankverzeichnis
.SH SYNOPSIS
.PP
The application is automatically started as service, listening on port
6006.
.IP
.nf
\f[C]
sudo\ service\ dbinfo\ {status|start|stop|restart}
\f[]
.fi
.SH INSTALLATION
.PP
The software is released as Debian package for Ubuntu 14.04 LTS.
Other Debian based distributions \f[I]might\f[] work too.
Releases can be found at <https://github.com/gbv/dbinfo/releases>
.PP
To install required dependencies either use a package manager such as
\f[C]gdebi\f[], manually install dependencies (inspectable via
\f[C]dpkg\ \-I\ dbinfo_*.deb\f[]):
.IP
.nf
\f[C]
sudo\ dpkg\ \-i\ ...\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ #\ install\ dependencies
sudo\ dpkg\ \-i\ dbinfo_X.Y.Z_amd64.deb\ \ \ \ #\ change\ X.Y.Z
\f[]
.fi
.PP
After installation the service is available at localhost on port 6006.
Better put the service behind a reverse proxy to enable SSL and nice
URLs! In the following a reverse proxy mapping
<http://uri.gbv.de/database/> to <http://localhost:6006/> is assumed.
.SH USAGE
.PP
GBV Datenbankverzeichnis provides a Linked Open Data endpoint with RDF
data in several serialization forms.
Serialization form can be controlled via content negotiation or via
query parameter \f[C]format\f[] (set to \f[C]ttl\f[], \f[C]json\f[],
\f[C]rdfxml\f[], \f[C]jsonld\f[] for RDF or \f[C]html\f[] for HTML by
default).
The RDF vocabularies are documented at a page accessible via
<http://uri.gbv.de/database/ontology.html>.
.PP
A convenient data format for reuse outside of RDF applications is
JSON\-LD:
.IP
.nf
\f[C]
curl\ http://uri.gbv.de/database/amb?format=jsonld
\f[]
.fi
.IP
.nf
\f[C]
{
\ \ \ "\@context"\ :\ "http://uri.gbv.de/database/dbinfo.jsonld",
\ \ \ "uri"\ :\ "http://uri.gbv.de/database/amb",
\ \ \ "title"\ :\ {
\ \ \ \ \ \ "de"\ :\ "Katalog\ der\ meereswissenschaftlichen\ Bibliotheken\ Deutschlands",
\ \ \ \ \ \ "en"\ :\ "German\ Association\ of\ Marine\ Science\ Libraries\ and\ Information\ Centers\ Catalogue"
\ \ \ },
\ \ \ "dbkey"\ :\ "amb",
\ \ \ "url":\ "https://gso.gbv.de/DB=2.910/",
\ \ \ "srubase"\ :\ "http://sru.gbv.de/amb",
\ \ \ "picabase"\ :\ "http://gsoapi.gbv.de/DB=2.910/",
\ \ \ "openaccess"\ :\ false
}
\f[]
.fi
.PP
Databases are grouped by prefixes which can be retrieved as JSKOS
concepts.
.PP
The service further provides an OpenSearch Suggest AI at
\f[C]/api/dbkey\f[] to query database prefixes:
.IP
.nf
\f[C]
curl\ http://uri.gbv.de/database/api/dbkey?id=opac\-de\-91
\f[]
.fi
.IP
.nf
\f[C]
[\ 
\ \ "opac\-de\-91",
\ \ ["opac\-de\-916"],
\ \ ["Online\-Katalog\ der\ Ostfalia\ Hochschule\ für\ angewandte\ Wissenschaften"],
\ \ ["http://uri.gbv.de/database/opac\-de\-916"]
]
\f[]
.fi
.SH ADMINISTRATION
.SS Configuration
.PP
Config file \f[C]/etc/default/dbinfo\f[] only contains basic server
configuration in form of simple key\-values pairs:
.IP \[bu] 2
\f[C]PORT\f[] \- port number (required, 6006 by default)
.IP \[bu] 2
\f[C]WORKERS\f[] \- number of parallel connections (required, 5 by
default).
.PP
Additional configuration is placed in \f[C]/etc/dbinfo/config.yml\f[]
with the following fields:
.IP \[bu] 2
\f[C]unapi\f[] \- base URL of unAPI config server to get databases from
.IP \[bu] 2
\f[C]proxy\f[] \- optional list of IPs or IP ranges the service can run
behind (for logging the proxied request IPs instead of proxy IP).
.IP \[bu] 2
\f[C]base\f[] \- base URI (\f[C]http://uri.gbv.de/database/\f[] by
default)
.IP \[bu] 2
\f[C]stats\f[] \- directory to store statistics in
(\f[C]/etc/dbinfo/stats\f[] by default).
.PP
Restart is required after changes.
.PP
The script \f[C]/etc/dbinfo/diagram.r\f[] is used to generate diagrams.
It can be adjusted locally, so updates to this script must be applied
manually!
.SS Database Statistics
.PP
Database statistics are stored in \f[C]/etc/dbinfo/stats\f[] (or in
another directory specified in configuration) in a CSV file for each
database.
This directory should be backed up to retain history data.
Statistics is updated daily via cronjob in
\f[C]/etc/cron.daily/dbinfo\f[].
.SS Logging
.PP
Log files are located at \f[C]/var/log/dbinfo/\f[]:
.IP \[bu] 2
\f[C]error.log\f[]
.IP \[bu] 2
\f[C]access.log\f[]
.IP \[bu] 2
\f[C]mkstat.log\f[]
.SH CHANGES
.PP
See \f[C]debian/changelog\f[].
.SH SEE ALSO
.PP
The source code of dbinfo is managed in a public git repository at
<https://github.com/gbv/dbinfo>.
Please report bugs and feature request at
<https://github.com/gbv/dbinfo/issues>!
.PP
The Changelog is located in file \f[C]debian/changelog\f[].
.PP
Development guidelines are given in file \f[C]CONTRIBUTING.md\f[].
